In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from warnings import simplefilter
# ignore all future warnings
simplefilter(action='ignore', category=FutureWarning)

In [2]:
%pwd

'D:\\Machine Learning\\Twitter Sentiment Analysis\\python-backend\\Pickel File Generation'

# Reading the CSV File

In [3]:
df = pd.read_csv("TwitterData.csv")
df.dropna()
df.head()

vader_neg  vader_neu  vader_pos  vader_compound  roberta_neg  roberta_neu   
0        0.0      1.000      0.000          0.0000     0.014746     0.928273  \
1        0.0      0.846      0.154          0.7906     0.003203     0.125370   
2        0.0      0.947      0.053          0.3384     0.001249     0.041221   
3        0.0      0.940      0.060          0.4215     0.005952     0.873916   
4        0.0      0.807      0.193          0.8519     0.002116     0.054837   

   roberta_pos Lang                                              Tweet   
0     0.056980   en  Tripura Chief Minister Manik Saha inspected th...  \
1     0.871427   en  I'd like to appreciate Ambassador Katherine Ta...   
2     0.957530   en  The ground rules of IPEF were laid out very we...   
3     0.120132   en  We also discussed progress of Indo-Pacific Eco...   
4     0.943047   en  I am delighted to share that we have made the ...   

        Tag     Score  
0  POSITIVE  0.564948  
1  POSITIVE  0.999794  
2  POSITIVE  0.999485  
3  POSITIVE  0.956361  
4  POSITIVE  0.999675

In [4]:
# To suffel the dataset
df.sample(frac=1)

# Reseting the Index
df.reset_index(drop=True, inplace=True)

# Change the Tag to numeric values
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Label'] = le.fit_transform(df['Tag'])

df.head()

vader_neg  vader_neu  vader_pos  vader_compound  roberta_neg  roberta_neu   
0        0.0      1.000      0.000          0.0000     0.014746     0.928273  \
1        0.0      0.846      0.154          0.7906     0.003203     0.125370   
2        0.0      0.947      0.053          0.3384     0.001249     0.041221   
3        0.0      0.940      0.060          0.4215     0.005952     0.873916   
4        0.0      0.807      0.193          0.8519     0.002116     0.054837   

   roberta_pos Lang                                              Tweet   
0     0.056980   en  Tripura Chief Minister Manik Saha inspected th...  \
1     0.871427   en  I'd like to appreciate Ambassador Katherine Ta...   
2     0.957530   en  The ground rules of IPEF were laid out very we...   
3     0.120132   en  We also discussed progress of Indo-Pacific Eco...   
4     0.943047   en  I am delighted to share that we have made the ...   

        Tag     Score  Label  
0  POSITIVE  0.564948      1  
1  POSITIVE  0.999794      1  
2  POSITIVE  0.999485      1  
3  POSITIVE  0.956361      1  
4  POSITIVE  0.999675      1

In [5]:
df = df.drop(['Lang', 'Tweet', 'Tag'], axis='columns')
df.shape

(65847, 9)

In [6]:
df.describe()

vader_neg     vader_neu     vader_pos  vader_compound   roberta_neg   
count  65847.000000  65847.000000  65847.000000    65847.000000  65847.000000  \
mean       0.084667      0.848391      0.066941       -0.036248      0.278212   
std        0.115770      0.130022      0.088870        0.501193      0.280132   
min        0.000000      0.000000      0.000000       -0.989100      0.000601   
25%        0.000000      0.769000      0.000000       -0.458800      0.022766   
50%        0.000000      0.863000      0.030000        0.000000      0.178379   
75%        0.145000      0.959000      0.113000        0.361200      0.500133   
max        0.721000      1.000000      1.000000        0.986800      0.975476   

        roberta_neu   roberta_pos         Score         Label  
count  65847.000000  65847.000000  65847.000000  65847.000000  
mean       0.578739      0.143048      0.944641      0.363175  
std        0.263320      0.238719      0.099335      0.480918  
min        0.006210      0.001597      0.500030      0.000000  
25%        0.365045      0.015314      0.950874      0.000000  
50%        0.614623      0.033925      0.986550      0.000000  
75%        0.812929      0.121036      0.996049      1.000000  
max        0.970903      0.992736      0.999888      1.000000

In [7]:
df.head()

vader_neg  vader_neu  vader_pos  vader_compound  roberta_neg  roberta_neu   
0        0.0      1.000      0.000          0.0000     0.014746     0.928273  \
1        0.0      0.846      0.154          0.7906     0.003203     0.125370   
2        0.0      0.947      0.053          0.3384     0.001249     0.041221   
3        0.0      0.940      0.060          0.4215     0.005952     0.873916   
4        0.0      0.807      0.193          0.8519     0.002116     0.054837   

   roberta_pos     Score  Label  
0     0.056980  0.564948      1  
1     0.871427  0.999794      1  
2     0.957530  0.999485      1  
3     0.120132  0.956361      1  
4     0.943047  0.999675      1

In [8]:
# Finding the corelation between the data
df_corr= df.corr()
df_corr

vader_neg  vader_neu  vader_pos  vader_compound  roberta_neg   
vader_neg        1.000000  -0.744408  -0.213557       -0.727430     0.601793  \
vader_neu       -0.744408   1.000000  -0.493345        0.196634    -0.349652   
vader_pos       -0.213557  -0.493345   1.000000        0.659923    -0.272368   
vader_compound  -0.727430   0.196634   0.659923        1.000000    -0.592405   
roberta_neg      0.601793  -0.349652  -0.272368       -0.592405     1.000000   
roberta_neu     -0.367960   0.422585  -0.138939        0.147454    -0.615642   
roberta_pos     -0.300312  -0.055825   0.472877        0.532527    -0.494394   
Score            0.093489  -0.096204   0.018959       -0.045245     0.180142   
Label           -0.345809   0.109116   0.290810        0.438538    -0.554596   

                roberta_neu  roberta_pos     Score     Label  
vader_neg         -0.367960    -0.300312  0.093489 -0.345809  
vader_neu          0.422585    -0.055825 -0.096204  0.109116  
vader_pos         -0.138939     0.472877  0.018959  0.290810  
vader_compound     0.147454     0.532527 -0.045245  0.438538  
roberta_neg       -0.615642    -0.494394  0.180142 -0.554596  
roberta_neu        1.000000    -0.380612 -0.272934  0.113208  
roberta_pos       -0.380612     1.000000  0.089669  0.525934  
Score             -0.272934     0.089669  1.000000 -0.062300  
Label              0.113208     0.525934 -0.062300  1.000000

### So, from here we can say that `vader_neg`	`vader_neu`	`vader_pos`	`vader_compound`	`roberta_neg`	`roberta_neu`	`roberta_pos` are independent variable and `Score` and `Label` are dependent variable





# Splitting the dataframe into Train And Test Dataframe  

In [9]:
X = df.drop(['Label', 'Score'], axis='columns')
Y_Regg = df.Score
Y_Classify = df.Label

In [10]:
from sklearn.model_selection import train_test_split

# For Regression
X_train_regg, X_test_regg, y_train_regg, y_test_regg = train_test_split(X, Y_Regg, test_size=0.2)

# For Clasification
X_train_classify, X_test_classify, y_train_classify, y_test_classify = train_test_split(X, Y_Classify, test_size=0.2)

In [11]:
X_train_regg.shape

(52677, 7)

In [12]:
X_test_regg.shape

(13170, 7)

# Multiple Linear Regression

Multiple linear regression is a statistical technique used to model the relationship between a dependent variable and multiple independent variables. It is an extension of simple linear regression, which models the relationship between a dependent variable and a single independent variable.


In [13]:
from sklearn import datasets, linear_model, preprocessing
from sklearn.metrics import mean_squared_error, r2_score

lrm = linear_model.LinearRegression()

In [14]:
lrm.fit(X_train_regg, y_train_regg)

LinearRegression()

In [15]:
lrm_predict = lrm.predict(X_test_regg)
lrm_predict

array([0.90951796, 0.98805733, 0.9755704 , ..., 0.99299186, 0.90930826,
       0.93395721])

In [16]:
y_test_regg

47587    0.943512
41929    0.999448
4124     0.997075
53823    0.982298
44175    0.997267
           ...   
64093    0.880947
49651    0.523837
13054    0.999824
60524    0.978767
32718    0.962691
Name: Score, Length: 13170, dtype: float64

In [17]:
print("Mean Squared Error - ", mean_squared_error(y_test_regg , lrm_predict))

Mean Squared Error -  0.00921139610866046


In [18]:
print("R-squared Value: ", r2_score(y_test_regg , lrm_predict))

R-squared Value:  0.07259605951487513


In [19]:
print("Coeficient", lrm.coef_)
print("Intercept", lrm.intercept_)

Coeficient [-1.73390935e+00 -1.71922363e+00 -1.74422792e+00  1.76905167e-03
 -9.98983011e+02 -9.99093423e+02 -9.98991941e+02]
Intercept 1001.7151724314973


In [20]:
 lrm.predict([[0.756, 0.244, 0.0, -0.4767, 0.91862196, 0.073102295, 0.008275842]])

D:\Machine Learning\Twitter Sentiment Analysis\python-backend\sentimentanalysis\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([0.99274989])

# KNN - K-Nearest Neighbors
K-Nearest Neighbors (KNN) is a simple and widely used non-parametric classification and regression algorithm. It is a supervised learning algorithm that can be used for both classification and regression problems.

In [21]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score


knn = KNeighborsClassifier()
knn.fit(X_train_classify, y_train_classify)

KNeighborsClassifier()

In [22]:
knn_predict = knn.predict(X_test_classify)
print(knn_predict)

[0 1 1 ... 0 0 0]


In [23]:
print(y_test_classify)

7530     0
3571     1
64474    1
15859    0
42032    0
        ..
36030    1
60717    0
37415    1
65260    0
14784    0
Name: Label, Length: 13170, dtype: int32


In [24]:
print("Mean Squared Error - ", mean_squared_error(y_test_classify , knn_predict))
accuracy = accuracy_score(y_test_classify , knn_predict)

print("Accuracy Percentage :", accuracy*100, "%")

Mean Squared Error -  0.1914958238420653
Accuracy Percentage : 80.85041761579348 %


# Random Forest

The Random Forest algorithm is a type of ensemble learning technique that combines multiple decision trees to make a prediction. In sentiment analysis, each decision tree can be trained on a subset of the available training data, with each tree making an independent prediction on the sentiment of a given piece of text. The final prediction is then made by combining the predictions of all the decision trees in the forest.

In [25]:
from sklearn.ensemble import RandomForestClassifier
rfa = RandomForestClassifier(n_estimators=100)
rfa.fit(X_train_classify, y_train_classify)

RandomForestClassifier()

In [26]:
rfa_predicted = rfa.predict(X_test_classify)
rfa_predicted

array([0, 1, 1, ..., 0, 0, 0])

In [27]:
print(y_test_classify)

7530     0
3571     1
64474    1
15859    0
42032    0
        ..
36030    1
60717    0
37415    1
65260    0
14784    0
Name: Label, Length: 13170, dtype: int32


In [28]:
print("Mean Squared Error - ", mean_squared_error(y_test_classify , rfa_predicted))
accuracy = accuracy_score(y_test_classify , rfa_predicted)

print("Accuracy Percentage :", accuracy*100, "%")

Mean Squared Error -  0.17372817008352315
Accuracy Percentage : 82.62718299164769 %


# Logistic Regression

Logistic Regression is a popular machine learning algorithm used for classification problems, where the goal is to predict whether a given input belongs to which possible classes. It is a supervised learning algorithm that models the probability of the input belonging to each class using a logistic function.

Here we are using Binary Classification since we have 2 Labels Positive and Negative

In [29]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()
lr.fit(X_train_classify, y_train_classify)

LogisticRegression()

In [30]:
lr_predict = lr.predict(X_test_classify)
print(lr_predict)

[0 1 1 ... 0 0 0]


In [31]:
print(y_test_classify)

7530     0
3571     1
64474    1
15859    0
42032    0
        ..
36030    1
60717    0
37415    1
65260    0
14784    0
Name: Label, Length: 13170, dtype: int32


In [32]:
# Predicting the probability that how much the tweet is Negative and Positive
lr.predict_proba(X_test_classify)

array([[0.98156744, 0.01843256],
       [0.23521679, 0.76478321],
       [0.1391031 , 0.8608969 ],
       ...,
       [0.51605351, 0.48394649],
       [0.96045303, 0.03954697],
       [0.93487154, 0.06512846]])

In [33]:
print("Mean Squared Error - ", mean_squared_error(y_test_classify , lr_predict))
accuracy = accuracy_score(y_test_classify , lr_predict)

print("Accuracy Percentage :", accuracy*100, "%")

Mean Squared Error -  0.18359908883826878
Accuracy Percentage : 81.64009111617312 %


# Exporting the Model

In [34]:
import pickle
models = {'lr' : lrm, 'knn' : knn, 'rf' : rfa , 'lr' : lr}

In [35]:
with open('TwitterSentimentModel', 'wb') as file:
  pickle.dump(models, file)

# Conclusion 

Now we can conclude that the accuracy scores and MSE by using the different algorithum are - 


---



### **Regression**
1.  Linear Regression - MSE - 0.00923519554216942

### **Classification**
1.  KNN - K-Nearest Neighbors - 81.71%
2.  Random Forest - 82.83%
3.  Logistic Regression - 82.98%